language: go

go:
  - 1.13.x
  - 1.15.x
  - 1.16.x

script: 
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - go test ./... -coverprofile cover.out
  - go tool cover -func cover.out